### PR TITLE
Add Nextcloud integration

### LINKED ISSUE #147: Nextcloud datasource support
Add support for nextcloud.

### PR DESCRIPTION
**Pull request by perry-mitchell**
Fixes #147

### CODE REVIEW

**Comment by perry-mitchell** [comment]
@sallar Did you have some way of testing nextcloud? I was not able to get this to work with the demo nextcloud installations.

@jancborchardt Did you know of any simple way to test nextcloud's webdav functionality without running up an entire server?

**Comment by sallar** [comment]
@perry-mitchell after you setup the demo account, the "endpoint" is: "https://demo.nextcloud.com/perry/" like so. (and append the /remote.php/webdav like owncloud). it works like that.

**Comment by perry-mitchell** [comment]
Thanks @sallar - Demo worked great and seems like it's stable. I'll merge.

**Comment by jancborchardt** [comment]
Awesome work, thanks a lot! :)

cc @jospoortvliet @karlitschek check it out, another awesome project with Nextcloud integration.

Since it’s a password manager (see https://buttercup.pw/), maybe there should be further integration with Passman? cc @brantje of https://github.com/nextcloud/passman

**Comment by brantje** [comment]
Didn't know how this password manager, will add a importer for passman for it =).

**Comment by perry-mitchell** [comment]
Thanks a lot @jancborchardt - it's great to have a product we can integrate with awesome open-source cloud storage solutions such as yours. Very interested in looking into it further. I'll checkout passback as well to see if we can also add an importer/exporter for it.

**Comment by brantje** [comment]
If needed, you can find me / us on freenode #nextcloud-dev

**Pull request merged**
